# Generated by Django 3.2.8 on 2021-10-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Todo',
        ),
    ]
